name: "Deployment"
on: workflow_call

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_FUNCTION_ARN: ${{ secrets.AWS_FUNCTION_ARN }}
      BUILD_ZIP_FILE: ${{ secrets.BUILD_ZIP_FILE }}
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Configure Deployment Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_LAMBDA_ROLE }}
          role-session-name: ${{ secrets.AWS_SESSION_NAME }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Download Build
        uses: actions/download-artifact@v4
        with:
          name: build
          path: build
      - name: Upload to Lambda
        run: bash ../.github/scripts/upload-code.sh
        working-directory: build
  deploy-edge:
    runs-on: ubuntu-latest
    needs: deploy
    env:
      AWS_CLOUDFRONT_DIST: ${{ secrets.AWS_CLOUDFRONT_DIST }}
      AWS_FUNCTION_ARN: ${{ secrets.AWS_FUNCTION_ARN }}
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Configure Deployment Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_EDGE_ROLE }}
          role-session-name: ${{ secrets.AWS_SESSION_NAME }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Deploy to edge
        run: bash ./.github/scripts/deploy-to-edge.sh
